# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumFacebookExampleUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumFacebookExampleUIKit
  #!!! NOTE: Import TealiumFacebook instead of below 
  pod 'TealiumFacebook', :path=> '/Users/christina/Projects/work-repos/github/tealium-ios-facebook-remote-command'
  pod 'tealium-swift/TealiumLogger'
  pod 'tealium-swift/TealiumTagManagement'
  pod 'tealium-swift/TealiumAppData'
  pod 'tealium-swift/TealiumDeviceData'
  pod 'tealium-swift/TealiumLifecycle'
end
