# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'TealiumFacebookExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumFacebookExample
  pod 'TealiumFacebook', :path=> '../'
  pod 'tealium-swift/Lifecycle'
  pod 'tealium-swift/TagManagement'

end
